jobs:
  call-check:
    secrets: inherit
    uses: SpongePowered/.github/.github/workflows/shared-check-spotless.yaml@master
    with:
      runtime_version: 17
name: Spotless Check
on:
  repository_dispatch:
    types: trigger-ga___check-spotless.yaml
