jobs:
  call-check:
    secrets: inherit
    uses: SpongePowered/.github/.github/workflows/shared-check-style.yaml@master
    with:
      runtime_version: 17
name: Checkstyle
on:
  repository_dispatch:
    types: trigger-ga___check-style.yaml
