jobs:
  call-build:
    secrets: inherit
    uses: SpongePowered/.github/.github/workflows/shared-ci.yaml@master
    with:
      publish_snapshot_javadoc: true
      publishing_branch_regex: api-\d+
      runtime_version: 17
name: Build, Test, and Deploy
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
